name: kraken-rs quick build and test x86_64
on:
  push:
    paths:
      - kraken-rs/src/**
    branches:
      - ISSUE-*
env:
  CARGO_TERM_COLOR: always
jobs:
  kraken-rs-quick-build-and-test-x86_64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: cargo build --manifest-path ./kraken-rs/Cargo.toml --verbose
      - name: Test
        run: cargo test --manifest-path ./kraken-rs/Cargo.toml --verbose
